<a href="https://colab.research.google.com/github/OscarDvr/Manejodedatos/blob/main/Main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="Teal" face="Comic Sans MS,arial">
  <h1 align="center"><i>MAIN</i></h1>
  </font>
  <h1 align="center"><i>Proyecto Final: Modelación de resultados sobre fútbol soccer por medio de la distribución Poisson</i></h1>
  </font>
  <font color="Black" face="Comic Sans MS,arial">
  <h5 align="center"><i>Daniela López Pavón</i></h5>
  <h5 align="center"><i>Oscar Daniel Vazquez Ramírez</i></h5>
    <h5 align="center"><i>Materia: Manejo de Datos</i></h5>
  </font>

# Predicciones finales de la liga española y su exactitud en cada modelo

In [135]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [136]:
%run './drive/MyDrive/Colab Notebooks/PreprocessingPMDD.ipynb'
%run './drive/MyDrive/Colab Notebooks/Functions.ipynb'

--2022-02-10 04:21:35--  https://github.com/daniela-elepe/Proyecto-Soccer-Model/blob/principal/TablaMF.csv
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘TablaMF.csv.4’

TablaMF.csv.4           [ <=>                ]   1.15M  --.-KB/s    in 0.05s

2022-02-10 04:21:35 (23.4 MB/s) - ‘TablaMF.csv.4’ saved [1207020]

Requirement already satisfied: import-ipynb in /usr/local/lib/python3.7/dist-packages (0.1.3)
--2022-02-10 04:21:39--  https://github.com/daniela-elepe/Proyecto-Soccer-Model/blob/principal/TablaMF.csv
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘TablaMF.csv.5’

TablaMF.csv.5           [ <=>                ]   1.15M  --.-KB/s    in 0.04s

2022-02-10 04:21:39 (29.0 MB/s) - ‘TablaMF.csv.5’ saved [1207021]

Requirement already satisfied: import-ipynb in /usr/local/lib/python3.7/dist-packages (0.1.3)
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# SOCCER_MODEL TEMPORADA BASE 2016

In [137]:
soccer_model(data_aux, 2016)

     Temporada  Div       Fecha  ...  P_Empate Preds  Resultados
0         2017  SP1  06/01/2017  ...  0.190944     L           E
1         2017  SP1  24/09/2017  ...  0.190944     L           L
2         2017  SP1  28/01/2017  ...  0.127658     L           L
3         2017  SP1  15/10/2017  ...  0.127658     L           E
4         2017  SP1  20/01/2017  ...  0.080012     L           E
..         ...  ...         ...  ...       ...   ...         ...
337       2017  SP1  15/01/2017  ...  0.221961     E           V
338       2017  SP1  04/02/2017  ...  0.207229     E           V
339       2017  SP1  21/08/2017  ...  0.141358     L           V
340       2017  SP1  27/04/2017  ...  0.303653     L           E
341       2017  SP1  25/11/2017  ...  0.303653     L           V

[342 rows x 12 columns]

# SOCCER_MODEL TEMPORADA BASE 2017

In [138]:
soccer_model(data_aux, 2017)

     Temporada  Div       Fecha  ...  P_Empate Preds  Resultados
0         2018  SP1  06/01/2018  ...  0.252183     L           L
1         2018  SP1  06/05/2018  ...  0.285980     E           V
2         2018  SP1  28/01/2018  ...  0.227943     L           E
3         2018  SP1  18/04/2018  ...  0.222316     L           V
4         2018  SP1  11/02/2018  ...  0.061196     L           E
..         ...  ...         ...  ...       ...   ...         ...
206       2018  SP1  12/05/2018  ...  0.355298     E           V
207       2018  SP1  13/01/2018  ...  0.277393     V           V
208       2018  SP1  08/04/2018  ...  0.296346     E           E
209       2018  SP1  29/04/2018  ...  0.264869     V           V
210       2018  SP1  19/04/2018  ...  0.221060     V           L

[211 rows x 12 columns]

# SOCCER_MODEL TEMPORADA BASE 2018

In [139]:
soccer_model(data_aux, 2018)

     Temporada  Div       Fecha  ...  P_Empate Preds  Resultados
0         2019  SP1  16/08/2019  ...  0.226918     E           L
1         2019  SP1  23/11/2019  ...  0.226402     E           V
2         2019  SP1  01/12/2019  ...  0.157889     L           V
3         2019  SP1  02/11/2019  ...  0.186213     E           L
4         2019  SP1  28/09/2019  ...  0.264254     L           V
..         ...  ...         ...  ...       ...   ...         ...
108       2019  SP1  27/09/2019  ...  0.219084     L           L
109       2019  SP1  15/12/2019  ...  0.287939     E           E
110       2019  SP1  02/11/2019  ...  0.082934     L           E
111       2019  SP1  25/08/2019  ...  0.123342     L           L
112       2019  SP1  20/10/2019  ...  0.131031     L           L

[113 rows x 12 columns]

# SOCCER_MODEL TEMPORADA BASE 2019

In [140]:
soccer_model(data_aux, 2019)

     Temporada  Div       Fecha  ...  P_Empate Preds  Resultados
0         2020  SP1  03/01/2020  ...  0.206887     L           E
1         2020  SP1  26/01/2020  ...  0.130346     L           E
2         2020  SP1  05/07/2020  ...  0.289734     L           V
3         2020  SP1  22/02/2020  ...  0.331204     L           L
4         2020  SP1  08/02/2020  ...  0.098621     L           L
..         ...  ...         ...  ...       ...   ...         ...
307       2020  SP1  18/01/2020  ...  0.177748     L           L
308       2020  SP1  22/06/2020  ...  0.211297     L           E
309       2020  SP1  09/07/2020  ...  0.271853     L           V
310       2020  SP1  31/10/2020  ...  0.271853     L           L
311       2020  SP1  04/10/2020  ...  0.091012     L           E

[312 rows x 12 columns]

# SOCCER_MODEL TEMPORADA BASE 2020

In [141]:
soccer_model(data_aux, 2020)

     Temporada  Div       Fecha  ...  P_Empate Preds  Resultados
0         2021  SP1  02/01/2021  ...  0.154387     L           L
1         2021  SP1  03/01/2022  ...  0.154387     L           L
2         2021  SP1  19/03/2021  ...  0.172757     L           L
3         2021  SP1  28/11/2021  ...  0.172757     L           L
4         2021  SP1  16/05/2021  ...  0.278206     L           L
..         ...  ...         ...  ...       ...   ...         ...
402       2021  SP1  23/10/2021  ...  0.111966     L           E
403       2021  SP1  19/12/2021  ...  0.097442     L           L
404       2021  SP1  08/01/2022  ...  0.125012     L           L
405       2021  SP1  31/10/2021  ...  0.343844     E           E
406       2021  SP1  04/12/2021  ...  0.041122     L           V

[407 rows x 12 columns]

In [142]:
import pandas as pd

colnames = ['Temporada','Fecha','Equipo_L', 'Equipo_V', 'Preds']
df = pd.DataFrame((soccer_model(data_aux, 2020)),
                               columns = colnames)

df.set_index(['Equipo_L', 'Equipo_V'], inplace = True)
df.loc['Valencia', 'Mallorca']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: PerformanceWarning: indexing past lexsort depth may impact performance.

                   Temporada       Fecha Preds
Equipo_L Equipo_V
Valencia Mallorca       2021  23/10/2021     L

In [143]:
soccer_model(data_aux, 2021)

TypeError: ignored

In [ ]:
filt_pred(apuesto_o_no(data_aux, '06/02/2022', 'Barcelona',2021))

In [ ]:
filt_pred(apuesto_o_no(data_aux, '06/02/2022', 'Real Madrid',2021))

In [ ]:
filt_pred(apuesto_o_no(data_aux, '06/02/2022', 'Betis',2021))

In [ ]:
filt_pred(apuesto_o_no(data_aux, '06/02/2022', 'Valencia',2021))

In [ ]:
filt_pred(apuesto_o_no(data_aux, '05/02/2022', 'Celta',2021))

In [ ]:
filt_pred(apuesto_o_no(data_aux, '05/02/2022', 'Osasuna',2021))

In [ ]:
def apuesto_o_no(temp, 'equipo_v', 'equipo_l'):
  colnames = ['Equipo_L', 'Equipo_V', 'Preds']
  df = pd.DataFrame((soccer_model(data_aux, temp)),
                                columns = colnames)

  df.set_index(['Equipo_L', 'Equipo_V'], inplace = True)
  df.loc[equipo_v, equipo_l]
  print(df)

In [ ]:
apuesto_o_no(2020, Valencia, Mallorca)

# SOCCER_MODEL TEMPORADA BASE 2021
# Predicciones para el 2022

In [ ]:
apuesto_o_no(data_aux, 2021, Celta, Levante)